# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pXvdgWjgFzpi9UsIi-XSk1z7xo_NXntz
"""

print("version 2.0")